version: '3'
services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    ports:
      - 27017:27017
    restart: always
    environment:
      - MONGODB_CONTAINER_NAME=mongodb

  automobile:
    build: ./app
    container_name: automobile
    ports:
      - 8000:8000
    depends_on:
      - mongodb
    environment:
      - MONGODB_CONTAINER_NAME=mongodb
      - REACT_APP_AUTOMOBILE_CONTAINER_NAME=automobile

  mikereact:
    build: ./react
    container_name: mike-react
    ports:
      - 3000:3000
    depends_on:
      - automobile
    environment:
      - REACT_APP_AUTOMOBILE_CONTAINER_NAME=automobile
